// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Fri Sep 11 11:48:17 2020

contador contador_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.buttonLeft(buttonLeft_sig) ,	// input  buttonLeft_sig
	.buttonRight(buttonRight_sig) ,	// input  buttonRight_sig
	.reset(reset_sig) ,	// input  reset_sig
	.outputData(outputData_sig) 	// output [9:0] outputData_sig
);

defparam contador_inst.MAX_VALUE = 640;
defparam contador_inst.MIN_VALUE = 0;
