// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Wed Mar 11 10:42:24 2020

controlUnit controlUnit_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.reset(reset_sig) ,	// input  reset_sig
	.opCode(opCode_sig) ,	// input [3:0] opCode_sig
	.printtingScreen(printtingScreen_sig) ,	// input  printtingScreen_sig
	.done(done_sig) ,	// input  done_sig
	.new_instruction(new_instruction_sig) ,	// output  new_instruction_sig
	.memory_wr(memory_wr_sig) ,	// output  memory_wr_sig
	.selectField(selectField_sig) ,	// output [3:0] selectField_sig
	.register_wr(register_wr_sig) ,	// output  register_wr_sig
	.selectorDemuxRegister(selectorDemuxRegister_sig) ,	// output  selectorDemuxRegister_sig
	.selectorDemuxData(selectorDemuxData_sig) ,	// output  selectorDemuxData_sig
	.selectorAddress(selectorAddress_sig) 	// output  selectorAddress_sig
);

defparam controlUnit_inst.PRONTO = 'b00;
defparam controlUnit_inst.ESCREVER_NO_BANCO = 'b01;
defparam controlUnit_inst.HABILITAR_IMPRESSAO = 'b10;
defparam controlUnit_inst.ESCRITA_NA_MEMORIA = 'b11;
