// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Mon Jun 24 14:16:25 2019

gameFSM gameFSM_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.reset(reset_sig) ,	// input  reset_sig
	.resetFSM(resetFSM_sig) ,	// input  resetFSM_sig
	.startGame(startGame_sig) ,	// input  startGame_sig
	.pauseGame(pauseGame_sig) ,	// input  pauseGame_sig
	.dead(dead_sig) ,	// input  dead_sig
	.dataout(dataout_sig) 	// output [2:0] dataout_sig
);

defparam gameFSM_inst.START = 'b00000;
defparam gameFSM_inst.PLAYING = 'b00001;
defparam gameFSM_inst.PAUSE = 'b00010;
defparam gameFSM_inst.RESET = 'b00011;
defparam gameFSM_inst.GAMEOVER = 'b00100;
