// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Tue Aug  6 22:40:15 2019

multiplex multiplex_inst
(
	.x1(x1_sig) ,	// input [10:0] x1_sig
	.y1(y1_sig) ,	// input [9:0] y1_sig
	.x2(x2_sig) ,	// input [10:0] x2_sig
	.y2(y2_sig) ,	// input [9:0] y2_sig
	.x3(x3_sig) ,	// input [10:0] x3_sig
	.y3(y3_sig) ,	// input [9:0] y3_sig
	.selector(selector_sig) ,	// input [1:0] selector_sig
	.out_x(out_x_sig) ,	// output [10:0] out_x_sig
	.out_y(out_y_sig) 	// output [9:0] out_y_sig
);

