// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Tue Apr 21 11:43:12 2020

multiplexador multiplexador_inst
(
	.selector(selector_sig) ,	// input  selector_sig
	.data(data_sig) ,	// input [data_bits1-1:0] data_sig
	.data2(data2_sig) ,	// input [data_bits2-1:0] data2_sig
	.out(out_sig) 	// output [out_bits_size-1:0] out_sig
);

defparam multiplexador_inst.data_bits1 = 32;
defparam multiplexador_inst.data_bits2 = 32;
defparam multiplexador_inst.out_bits_size = 32;
