// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Thu Jun 27 22:45:31 2019

phrases phrases_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.reset(reset_sig) ,	// input  reset_sig
	.ready(ready_sig) ,	// input  ready_sig
	.videoEnable(videoEnable_sig) ,	// input  videoEnable_sig
	.letterColor(letterColor_sig) ,	// input [8:0] letterColor_sig
	.pixel_x(pixel_x_sig) ,	// input [10:0] pixel_x_sig
	.pixel_y(pixel_y_sig) ,	// input [9:0] pixel_y_sig
	.letters(letters_sig) ,	// input [7:0] letters_sig
	.address(address_sig) ,	// input [12:0] address_sig
	.colors(colors_sig) ,	// output [8:0] colors_sig
	.dataReady(dataReady_sig) 	// output  dataReady_sig
);

