// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Thu Apr 23 12:13:18 2020

registerFile registerFile_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.n_reg(n_reg_sig) ,	// input [4:0] n_reg_sig
	.check(check_sig) ,	// input [18:0] check_sig
	.data(data_sig) ,	// input [31:0] data_sig
	.written(written_sig) ,	// input  written_sig
	.selectField(selectField_sig) ,	// input [3:0] selectField_sig
	.out_readData(out_readData_sig) ,	// output [31:0] out_readData_sig
	.success(success_sig) 	// output  success_sig
);

defparam registerFile_inst.offset_inicio = 0;
defparam registerFile_inst.offset_final = 'b01000;
defparam registerFile_inst.y_inicio = 'b01001;
defparam registerFile_inst.y_final = 'b010001;
defparam registerFile_inst.x_inicio = 'b010010;
defparam registerFile_inst.x_final = 'b011011;
defparam registerFile_inst.spriteLine = 20;
