// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Sat Jul  6 08:10:58 2019

spriteMoveFSM spriteMoveFSM_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.reset(reset_sig) ,	// input  reset_sig
	.left(left_sig) ,	// input  left_sig
	.right(right_sig) ,	// input  right_sig
	.up(up_sig) ,	// input  up_sig
	.down(down_sig) ,	// input  down_sig
	.dataout(dataout_sig) 	// output [2:0] dataout_sig
);

defparam spriteMoveFSM_inst.DEF_STATE = 'b00000;
defparam spriteMoveFSM_inst.LEFT_STATE = 'b00000;
defparam spriteMoveFSM_inst.RIGHT_STATE = 'b00000;
defparam spriteMoveFSM_inst.UP_STATE = 'b00000;
defparam spriteMoveFSM_inst.DOWN_STATE = 'b00000;
