// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Thu Apr 23 11:25:47 2020

sprite_memory sprite_memory_inst
(
	.address(address_sig) ,	// input [13:0] address_sig
	.clock(clock_sig) ,	// input  clock_sig
	.data(data_sig) ,	// input [8:0] data_sig
	.wren(wren_sig) ,	// input  wren_sig
	.out_data(out_data_sig) ,	// output [8:0] out_data_sig
	.read_memory(read_memory_sig) 	// output  read_memory_sig
);

