// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Wed Jul 22 18:51:19 2020

video_processor video_processor_inst
(
	.clk_FPGA(clk_FPGA_sig) ,	// input  clk_FPGA_sig
	.clk_en(clk_en_sig) ,	// input  clk_en_sig
	.reset(reset_sig) ,	// input  reset_sig
	.start(start_sig) ,	// input  start_sig
	.dataA(dataA_sig) ,	// input [31:0] dataA_sig
	.dataB(dataB_sig) ,	// input [31:0] dataB_sig
	.R(R_sig) ,	// output [2:0] R_sig
	.G(G_sig) ,	// output [2:0] G_sig
	.B(B_sig) ,	// output [2:0] B_sig
	.out_hsync(out_hsync_sig) ,	// output  out_hsync_sig
	.out_vsync(out_vsync_sig) ,	// output  out_vsync_sig
	.out_printtingScreen(out_printtingScreen_sig) 	// output  out_printtingScreen_sig
);

